name: Run changeset

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".changeset/**.md"

jobs:
  run-changeset:
    name: Run changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.28

      - name: Install dependencies
        run: bun install

      - name: Rollup
        run: bun run ci:packages:rollup

      - name: Run changeset
        uses: changesets/action@v1
        with:
          publish: bun changeset publish
          commit: "chore(packages): version packages"
          title: "chore(packages): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
