name: Run changeset

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".changeset/**.md"

jobs:
  run-changeset:
    name: Run changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.28

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run ci:packages:rollup

      - name: Authenticate npm
        run: |
          echo "auto-install-peers=true" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Run changeset
        uses: changesets/action@v1
        with:
          publish: bun changeset publish --contents ./dist
          commit: "chore(packages): version packages"
          title: "chore(packages): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
